### ISSUE TITLE
Add default Fastlane install

### ISSUE THREAD

**Issue by vincentbrison** [faberNovel/docker-android#49]
As we already providing default ruby env, and default bundler install, we should provide a default Fastlane install.

It would allow faster setup to user using the same version, and does not want to rely on ruby cache install.

It would also make sense in the context of using the docker image as a dedicated GitHub Action (see #45)

**Comment by vincentbrison** [comment]
Any thoughts @sjcqs?

**Comment by sjcqs** [comment]
It would have to be updated every time fast lane is updated.

I'm not sure how much time could be saved by providing a default version

**Comment by vincentbrison** [comment]
It makes sense. I will keep this open, so we can discuss it, maybe when image as action will be ready, since it would be the main use case. Will see!

**Comment by sjcqs** [comment]
There's an issue if we provide fastlane out-of-the-box: 
- Versioning: the project would have to use the version available in the image. Which mean we would have to keep track of new fastlane version and update images as often as possible. 
This should be the responsibility of the project to say which fastlane version it needs. 

Maybe, we can instead add an option like `run_bundle_install` to the Github Action to run `bundle install` so that fastlane and any dependencies will be installed by the action inside the entrypoint. 
Or even `install_fastlane` which would either:
- Run bundle install if a Gemfile is detected
- Install fastlane if no Gemfile is detected

I don't think there's a lot of added value though 🤔

**Comment by vincentbrison** [comment]
Yes, not sure its a good idea, as installing Fastlane is fast (few seconds) and can be cached, VS ruby install for example, which can takes few minutes.

For me it is up to the image / action consumer to define its workflow, which maybe does not involve fastlane at all. So we could add such option as `run_bundle_install` but at the end, we may hide through this behavior, which can leads to confusion.

**Comment by vincentbrison** [comment]
Can I close this issue @sjcqs? We could re-open and re-evaluate our mind if someone comes with new ideas at the table.
